version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: devdb
    ports: [ "5432:5432" ]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: bash -c "pnpm install && pnpm dev"
    ports: [ "3000:3000" ]
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/devdb
    depends_on: [ db ]
    volumes:
      - .:/workspaces/your-next-app
    working_dir: /workspaces/your-next-app
  prisma-studio:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: npx prisma studio --browser none --port 5555
    ports: [ "5555:5555" ]
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/devdb
    depends_on: [ db ]
    volumes:
      - .:/workspaces/your-next-app
    working_dir: /workspaces/your-next-app
volumes:
  pgdata: